version: '3.8'

services:
    metabase:
      container_name: frontend-metabase
      restart: unless-stopped
      image: metabase/metabase
      ports:
        - "3000:3000"
      environment:
        - MB_DB_TYPE=postgres
        - MB_DB_DBNAME=metabase
        - MB_DB_PORT=5432
        - MB_DB_USER=metabase_user
        - MB_DB_PASS=BTgfsBDWmOBu
        - MB_DB_HOST=master.9756f677-ce7c-4259-8206-8e19d169093d.c.dbaas.selcloud.ru
      deploy:
        resources:
          limits:
            memory: 2g
