version: '3.8'

services:
  node:
    container_name: FastAPI
    restart: unless-stopped
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    networks:
      - node_network


networks:
  node_network: