# Test your FastAPI endpoints


GET http://127.0.0.1:8000/api/invoices?day=2024-02-20
Accept: application/json

###
PUT http://127.0.0.1:8000/api/drivers_place
Accept: application/json
Content-Type: application/json

{"date":"2024-02-20","car_id":18,"driver_id":61,"fio":"Ахунов Алексей Анатольевич","plate_number":"О183ОМ196 MERCEDES-BENZ ACTROS 2645 LS","id":288}

###