user root;
worker_processes  1;

events {
}

http {
    server {
            listen 80;
            listen [::]:80;

            server_name testing.rwtarif.com 77.223.107.196;

            location / {
                proxy_pass http://node:3000;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_cache_bypass $http_upgrade;

            }
            location /api/ {
                proxy_pass http://backend:8000/api/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_cache_bypass $http_upgrade;

            }
        error_log /var/log/nginx/error.log debug;
        access_log /var/log/nginx/access.log;
    }


}
